### ISSUE TITLE
Tag de fechamento section

### ISSUE THREAD

**Issue by gigante762** [especializati/larafood#6]
O aquivo é o larafood/resources/views/admin/pages/plans/details/show.blade.php

linha 15 está @stop em vez de @endsection.
Há em em outros também. Todos os que usaram o primeiro modelo com esse 'erro'.

Não abri pull request pra não ficar aparecendo no projeto. Além do mais, exelente curso!

**Comment by carlosfgti** [comment]
A diretiva @stop para fazer o fechamento também é válido :-)

Em qui., 8 de abr. de 2021 às 14:50, gigante762 ***@***.***>
escreveu:
